semantalytics/awesome-semantic-web

README.md

Adding CARML to RML

---

README.md

add ruby-rdf as language specific resource
add programming to table of contents

add ruby specific resource page

---

README.md

Adding metaphacts to companies section

---

README.md

`markdown-toc README.md --no-firsth1 --maxdepth=2`

TOC maxdepth=2

---

README.md

Reverts semantalytics/awesome-semantic-web#44
Looks ugly :/

Revert "aesthetics for DB section"

---

README.md

DBPedia -> DBpedia
RDFUnit description

some descriptions improvements

---

README.md

Behind the scenes changes. Working towards linter CI pipeline.
Very little context changes, that came up as result of inspecting linter errors.
Refactoring of  `RDB to RDF` and `CSVW` sections.

Issue 48/markdownlint

---

README.md

Demystifying OWL for the Enterprise

Added one more book

---

README.md

Schneider Electric is actively using Semantic Web technologies for its products. It released ontology SDK called OLGA as open source in 2018 (https://github.com/EcoStruxure/OLGA)

included Schneider Electric in Industry section

---

README.md

Karma is a data integretaion tool which supports the mapping of various data formats into rdf.
It should be listed on the site because it provides a user-friendly interface for the mapping and data transformation.
More information here: http://usc-isi-i2.github.io/karma/

Add Karma to Mapping Section

---

README.md

Static types generated from some common vocabularies

Added a .net tool I built

---

README.md

I would like to propose a C# library I've developed for modeling and validating OWL-DL/SKOS ontologies. Thanks.

Propose .NET library for Ontology Development

---

README.md

US2TS is a community conference for the North American semantic web community across fields and disciplines.

Adds US2TS conference

---

README.md

From its README:
> Whelk is implemented as an immutable functional data structure, so that each time axioms are added, a new reasoner state is created. References to the previous state remain unchanged. This allows Whelk to answer queries concurrently, and also allows rapid classification of multiple datasets which build upon the same ontology Tbox, which can be classified ahead of time and stored. However, for basic classification of a single ontology, Whelk is much slower than ELK.
> In addition to OWL EL classification, Whelk provides OWL RL and a subset of SWRL for reasoning on individuals.

Adds Whelk, an OWL EL reasoner for concurrent query answering

---

README.md

Adding sparqlprog

---

README.md

Added ODK, ROBOT, and dosdp-tools

Add ODK, ROBOT, dosdp-tools

---

README.md

Added three RDF JS libraries, a Ruby library and a linked data blog

Add @ontologies, rdfdev-js, ontola, rdf-serializers

---

README.md

eliminated a duplicate of umls2rdf, added BioPortal, OntoPortal, and CEDAR

added Stanford BMIR resources

---

README.md

added an awesome list focus on semantic web for GLAM (Gallery, Library, Museum and Archive) sector.  Quite similar, but many more resources developed and use in the heritage/digital humanities communities

added other awesome

---

README.md

Added OOPS!, an online system for ontology evaluation

added OOPS!

---

README.md

DCA = data-centric architecture

adding Semantic Arts, the gist ontology, and books on ontology engineering & DCA

---

README.md

Added links to the Cameo Concept Modeler in the ontology-development and visualization sections.

Added Cameo Concept Modeler

---

README.md

fix ONT-API link

---

README.md

Extended supported languages to Turtle* and SPARQL*

Update Linked Data syntaxes description

---

README.md

and add a link to the paper which describes what "re-engineering" is.

Sparql anything

---

README.md

Create a section "Government" after "Industry" and add in a couple of entries

Government section with entries

---

README.md

Adding a series of [rdflib](https://github.com/RDFLib/rdflib)-based tools to the list

rdflib-based tools

---

README.md

Add GeoSPARQL

---

README.md

Thanks for this awesome list, I hope these additions are useful.

Adding json-rql and m-ld

---

README.md

Add an Australian Semantic Web / Linked Data company

add SURROUND

---

README.md

Add tools from https://rml.io:
- RMLMapper
- RMLStreamer
- RMLEditor Community Editon
- UnSHACLed

README: add RMLMapper, RMLStreamer, RMLEditor and UnSHACLed

---

README.md

Removed duplicate link to Derivo

Added link to AtomGraph

---

README.md

Added the Knowledge Graph Conference - KGC

---

README.md

Fix a typo ("Working") for the title of https://www.linked.data.gov.au

Add galacteek in "Browsers" section

---

README.md

Tbh, not sure if a subcategory is a better fit.

Add ShExML

---

README.md

- [ont-converter](https://github.com/sszuev/ont-converter)
- [rdf-protege](https://github.com/sszuev/rdf-protege)

add ont-converter and rdf-protege tools (#150)

---

README.md

Sentence: 
"Pull requests will be evaluated immediately for inclusion **while posts while awesomelets** will be evaluated at some indeterminate time in the future."
Corrected to: 
"Pull requests will be evaluated immediately for inclusion **while awesomelets** will be evaluated at some indeterminate time in the future."

updated small grammatical error in readme

---

README.md

Either the project got renamed or the initial name was incorrect from the beging

Rename Supernatural to Sparnatural

---

README.md

Add a common open book on ontology engineering by Maria Keet

Add book: An Introduction to Ontology Engineering by keet

---

README.md

Update README.md add RDF4j

---

README.md

* Adds HeFQUIN in both the Federation section and the Linked Data Fragments section
* Adds the Semantic Web group at Linköping University to the Research Institutions section

Adds HeFQUIN and the SemWeb group at Linköping University

---

README.md

add to the list of conferences:
- ICBO
- US2TS

add to conferences list

---

README.md

to list of Educational resources

add link to OBO Academy

---

README.md

UltraGraphQL and Grasp are promising libraries to access semantic data using a GraphQL API

add GraphQL projects to the list

---

README.md

Versioned triple store backed by FoundationDB

Add Copernic

---

README.md

Add awesome-ontology list

---

README.md

Update README.md - Apache Any23 is retired

---

README.md

remove double entry of zazuko in the company section

Fix double entry of company/zazuko

---

README.md

This PR updates the reference of the old **RDFSharp.Semantics** .NET ontology library to the new **OWLSharp**

Update old reference

---

README.md

Lightweight store with some limitations.

Add Tentris to databases

---

README.md

updates for mobi information and links

Mobi Information Updates

---

README.md

An awesome collection of different tools to quickly validate or play around with your graphs

Add RDF Playground

---

README.md

Applied Ontology 
Journal of Biomedical Semantics

Added two journals to Academic section

---

README.md

Lowcode tool to connect linked data resources and applied transformations on structured data sources

Add Silk Linked data integration framework

---

README.md

A tool to visualize KGs in the browser, developed by HTWK SWE Group Leipzig

Add Kingvisher

---

README.md

Software Engineering Group of HTWK Leipzig, works on linked data and rdf based solutions for material sciences and industry

Add SWE Group of HTWK

---

README.md

Easy to use SHACL validator, provide your data and shapes and get a report

Add Zazuko's SHACL Playground

---

README.md

Add ontogen a rdf aware VCS. With PROV and DCAT support to the devops section

Add Ontogen

---

README.md

Add the Company fluree to the list. one of their products is already listed (fluree core) under databases, But since they provide multiple tools all based around rdf and json-ld they should also be listed as an provider.

Add Fluree to companies

---

README.md

Actually not sure if #Java might be a better fit
Framework for mapping RDF data to Java objects using annotations, enabling object-oriented interaction with RDF models.

Add KOMMA RDF JAVA Object mapper

---

README.md

* new company
* new triplestore
* new API
Well, new for this list, not new in the real world!

several updates

---

README.md

Language Server for VSCode and other editors implementing the Language server proto.

Add Semantic Web LSP

---

README.md

A SPARQL Engine that can also access other data source at query time and bind results to variables within the query
#eswc2025

Add SPARQLLM

---

README.md

Add rdfless to the tools section
