semantalytics/awesome-semantic-web

README.md

Eclipse Lyo supports Java developers with the development of REST-based servers and clients that need to share heterogeneous information as RDF resources. It supports Linked Data principles and OSLC.

Added link to Eclipse Lyo

---

README.md

Added a new sub section for Elixir at the end of the Programming languages section. (I find the ordering of the programming languages quite random and would generally prefer a more neutral ordering, like alphabetically.)

Add RDF.ex

---

README.md

Add [Beam](https://github.com/eBay/beam) to databases list. It is an open source distributed knowledge graph store written in Go. Beam was written and used in eBay.

Add Beam to databases list

---

README.md

Add links to JOPA - an object-triple mapping library (OTM) and the OTM benchmark to the awesome list.

Add links to JOPA and OTM benchmark

---

README.md

Added the following programming resources:
- [sparql-engine](https://github.com/Callidon/sparql-engine) - An open-source framework for building SPARQL query engines in Javascript/Typescript.
- [pyHDT](https://github.com/Callidon/pyHDT) - Read and query [HDT documents](http://www.rdfhdt.org/) with ease in Python

Add sparql-engine & pyHDT as programming resources

---

README.md

added SPARQL to Gremlin mapping/translation resources:
- Apache TinkerPop sparql-gremlin plugin
- Gremlinator standalone translator

added SPARQL to Gremlin mapping/translation resources

---

README.md

- Added a description for WIDOCO (it was empty)
- Added OnToology (which allows creating/maintaining documentation + testing + publication of ontologies  from a GitHub repository)
- Added  OBA, a framework for transforming OWL into a OpenAPI REST API.

Update README.md with 1 tool update and 2 new tools

---

README.md

Atomic Data is a new specification with a couple of open source libraries that aims to make it easier to work with RDF. It uses a strict subset of RDF, which in turn enables type safety, better performance and higer interoperability.
Read more about the project in the [docs](https://docs.atomicdata.dev/)

Add Atomic Data projects

---

README.md

The latest version of R2RML-F is to be found on the main developer's
repository.

Changed link to repository R2RML-F

---

README.md

This PR adds a CSVW section as per [issue 105](https://github.com/semantalytics/awesome-semantic-web/issues/105).
I've also added some related tools to other relevant sections.
Arguably we could consolidate this with the two other tabular sections - "Standards > Tabular" and "Mapping > CSV/Tabular". I'm not sure what the best approach for that would be so have started with the simplest thing for now - introducing a CSVW section.

Introduce CSVW section, adding related tools elsewhere too

---

README.md

I have added a reference to the GeoSPARQL compliance benchmark:
https://github.com/OpenLinkSoftware/GeoSPARQLBenchmark
which has also been published as a paper here:
https://www.mdpi.com/2220-9964/10/7/487

Added GeoSPARQL Compliance benchmark

---

README.md

triplify-csv. A python package and CLI that will generate triples or nquads from csv files and a configuration file that uses a subset of the r2rml terms.

Request to add triplify-csv

---

README.md

Added an entry in the Mapping section to G2GML.
G2GML maps RDF graphs to property graphs and supports several formats for materialization of the property graph.

Adds G2GML property graph rdf mapper

---

README.md

The provided link was broken and resulted in a 404
Fixed by providing a recent link to the original publisher and an alternative to Springer

Fix link Book: Demystifying OWL for the Enterprise

---

README.md

The project is called ARC2 and their main developer is @semsol.
Source: https://github.com/semsol/arc2#arc2

Fixed name of PHP library (semsol => ARC2)

---

README.md

Unfortunately, both the original repos
- https://github.com/ethz-asl/libfactplusplus
- https://bitbucket.org/dtsarkov/factplusplus
are currently abandoned, so this is our attempt to revive the activity.

Add *pyfactxx* FaCT++ upgrade for Python and RDFLib datatypes / typical reasoning scenarios

---

README.md

At Field 33 we are building a platform to build digital twins of organizations, with many semantic web technologies at the core of our stack.
As one of the core components to our solution we've built an ontology package manager with [Plow](https://plow.pm). For both Plow and our platform we've also built up some open source Rust libraries that might be of interest to others.

Add Field33/Plow and our Rust libraries

---

README.md

I added links to further PHP libraries, which are still maintained and actively developed. The organization **sweetrdf** is managed by @zozlak and myself (source: https://github.com/sweetrdf). We are the maintainers of the libraries I mentioned, so feel free to ask, if there is something missing.
CC @zozlak

Programming > PHP: added sweetrdf libraries

---

README.md

RhizomerEye allows publishing and exploring semantic data from SPARQL endpoints. ReDeFer includes tools to map RDF to SVG and HTML, plus XML to RDF and XSD to OWL.

Add Rhizomer and ReDeFer tools

---

README.md

The university of freiburg has two labs that have already contributed a lot to the semantic web community and two of their projects are already included in this list

Add Semantic web related labs from Freiburg

---

README.md

Proposal to add:
- the Chimera tool (https://github.com/cefriel/chimera) an open-source framework implemented on top of Apache Camel and offering components to define schema and data transformation pipelines based on Semantic Web solutions 
- the mapping-template tool (https://github.com/cefriel/mapping-template) a template-based component exploiting Apache Velocity to define mappings to/from RDF

Add Cefriel tools

---

README.md

https://github.com/validatingrdf/validatingrdf.github.io/wiki/Updated-list-of-implementations and https://github.com/w3c/shacl/issues/78

add links to SHACL implementations

---

README.md

The comunica framework was miss-typed as communica.

Fix Typo in Term

---

README.md

RiverBench is an open and collaborative benchmark suite for streaming and non-streaming RDF systems: https://w3id.org/riverbench/
I've also fixed up table of contents and the headings to match each other, now I think it makes a bit more sense. Not all of these benchmarks include SPARQL queries, so it doesn't make sense to put them there. Later we probably should categorize the benchmarks...

Add RiverBench, an open benchmark suite

---

README.md

Added a link to the RDF Stream Taxonomy, which also includes a small ontology to describe RDF stream types. The RDF-STaX website also hosts a living literature review of RDF streaming, which uses the nanopublication system.

Add the RDF Stream Taxonomy (RDF-STaX)

---

README.md

I've added Jelly, a high-performance binary format which works not only for flat RDF files, but also for RDF streams: https://w3id.org/jelly
I've also moved RDF Thrift from the miscellaneous section up to RDF serialization formats, where it belongs :)

Add the Jelly serialization format

---

README.md

EasyRdf repository has [8 open pull requests](https://github.com/easyrdf/easyrdf/pulls) and the author being inactive for over 2 years. There is no development and feedback (latest commit is from Aug 31, 2021). In my opinion this situation means the project is abandoned.
The fork I added is maintained by myself and aims for users, who are forced to use EasyRdf. Because EasyRdf is not maintained anymore, there are no adaptions for PHP 8.1+. My fork closes that gap and contains further tweaks and optimizations also.

Added fork to abandoned EasyRdf project (PHP)
